### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by katavie** [mdn/to-do-notifications#2]
Is this under the same license as the MDN wiki docs, Creative Commons Attribute-ShareAlike? I'd like to adapt the IndexedDB code for a personal project I'm doing to test the speed of different data storage methods.

**Comment by chrisdavidmills** [comment]
Hi there!

This was always my understanding about the license this code should be under, but we should probably make this clear somewhere. I've started a discussion in the MDN community to verify the details and get this resolved.

for the time being, I am happy to give you my blessing on behalf of MDN to reuse this particular code under the license you stated.

**Comment by chrisdavidmills** [comment]
Update - the official answer is even better than I expected. MDN code samples are actually public domain (i.e. CC0), so you can copy and paste them without needing attribution or sharealike.

**Comment by katavie** [comment]
Alright, thank you!
