### ISSUE TITLE
TypeError: db is undefined

### ISSUE THREAD

**Issue by MawiaHL** [mdn/to-do-notifications#6]
Is this a bug or an issue with the latest version of firefox?

**Comment by chrisdavidmills** [comment]
I've just tried https://mdn.github.io/to-do-notifications/ in the latest Firefox Nightly, and it seems to work fine for me. Which version are you using? Also, are you trying to run it locally, or online?

**Comment by MawiaHL** [comment]
I am using firefox 65.0 (64bit).

**Comment by teoli2003** [comment]
I've been using this on Firefox for weeks (for different reasons), and this is working.

I'm closing this issue. If the problem is still there, feel free to reopen a new issue.
