### ISSUE TITLE
You should consider change the demo bck color

### ISSUE THREAD

**Issue by 3x0dv5** [mdn/to-do-notifications#9]
That yellow background is killing my eyes, it actually makes me dizzy....
http://mdn.github.io/to-do-notifications/

**Comment by teoli2003** [comment]
@dubeyji10 You [expressed an interest](https://github.com/mdn/to-do-notifications/pull/20#issuecomment-1067520659) in fixing the colours. PR welcome if you are still interested.

(I'd better not choose the new colours myself. I'm less flashy than the original writer, but I was told that my taste is… odd).

**Comment by 3x0dv5** [comment]
I'm sorry, I don't know where I had my head, I should've had simply added the PR in the first place.
